# Generated by Django 4.0.2 on 2022-03-02 06:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('posting_date', models.DateField(auto_now_add=True)),
                ('updation_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=40, unique=True)),
                ('posting_date', models.DateField(auto_now_add=True)),
                ('country_desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('updation_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=40, unique=True)),
                ('state_desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('posting_date', models.DateField(auto_now_add=True)),
                ('updation_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(regex='^(\\+\\d{1,3})?,?\\s?\\d{8,13}')], verbose_name='Mobile Number')),
                ('address', models.CharField(blank=True, max_length=1024, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('user_type', models.CharField(blank=True, choices=[('1', 'Public'), ('2', 'Municipality')], default=1, max_length=12, null=True)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.state')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality_name', models.CharField(max_length=100)),
                ('municipality_address', models.CharField(max_length=500)),
                ('municipality_desc', models.TextField(blank=True, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(regex='^(\\+\\d{1,3})?,?\\s?\\d{8,13}')], verbose_name='Contact Number')),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('posting_date', models.DateField(auto_now_add=True)),
                ('updation_date', models.DateField(auto_now=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.state')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint_Sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=100)),
                ('sub_category_desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('posting_date', models.DateField(auto_now_add=True)),
                ('updation_date', models.DateField(auto_now=True)),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.complaint_category')),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_subject', models.CharField(blank=True, max_length=500, null=True)),
                ('complaint_details', models.TextField(blank=True)),
                ('complaint_file', models.ImageField(blank=True, null=True, upload_to='')),
                ('complaint_status', models.CharField(choices=[('1', 'Pending'), ('2', 'Processing'), ('2', 'Closed')], default=1, max_length=10)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('updation_date', models.DateField(auto_now=True)),
                ('complaint_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.complaint_category')),
                ('complaint_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.complaint_sub_category')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.municipality')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.state')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
