# Generated by Django 4.0.2 on 2022-03-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_category',
            name='category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='complaint_sub_category',
            name='sub_category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
