# Generated by Django 4.0.2 on 2022-03-21 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_complaint_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_sub_category',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.complaint_category'),
        ),
    ]
