# Generated by Django 4.0.2 on 2022-03-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_complaint_sub_category_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='complaint_status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Processing'), ('3', 'Closed')], default=1, max_length=10),
        ),
    ]
