# Generated by Django 4.0.2 on 2022-03-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_complaintremarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintremarks',
            name='remarks_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
