# Generated by Django 4.0.2 on 2022-03-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_complaintremarks_remarks_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='complaint_status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Processing'), ('3', 'Closed')], max_length=10),
        ),
    ]
