# Generated by Django 4.0.2 on 2022-03-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_complain_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintremarks',
            name='complaint_status',
            field=models.CharField(blank=True, choices=[('2', 'Processing'), ('3', 'Closed')], max_length=10, null=True),
        ),
    ]
