# Generated by Django 4.0.2 on 2022-03-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_reg_user',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
