# Generated by Django 4.0.2 on 2022-03-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_feedback_is_reg_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
