# Generated by Django 4.0.2 on 2022-04-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_feedback_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='complaint_status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Processing'), ('3', 'Closed')], default=1, max_length=10),
        ),
    ]
